version: "3.4"
services:
  api-server:
    links: 
      - sql-server-db:sql-server-db
    build: 
      context: ./docker/api-server
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
       - sql-server-db
    
  sql-server-db:
    image: deploy_sql-server-db
    build:
      context: ./docker/sql-server-db
      dockerfile: Dockerfile
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
    volumes:
      - './db_storage:/var/opt/mssql'

