version: "3.3"
services:
  sql-server-db:
    image: deploy_sql-server-db
    build:
      context: ./docker/sql-server-db
      dockerfile: Dockerfile
    environment:
      SA_PASSWORD: "1Secure*Password1"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1434"
    volumes:
      - './db_storage:/var/opt/mssql'

  api-server:
    build: 
      context: ./docker/api-server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
       - sql-server-db
